### ISSUE TITLE
contact & blog 

### ISSUE THREAD

**Issue by faisaalalhaj** [YacoubAl-hardari/portfolio-with-Filament#1]
tried to fill than submit the contact me form and it shows that does not send 

when i try to create a new article
![image_2024-02-23_031127525](https://github.com/YacoubAl-hardari/portfolio-with-Filament/assets/154662147/f099f6b9-8b00-4e5a-8ef2-8dd8f94a1681)
 in blog it shows page not found 404

**Comment by YacoubAl-hardari** [comment]
Fixed
