### ISSUE TITLE
php error 

### ISSUE THREAD

**Issue by faisaalalhaj** [YacoubAl-hardari/portfolio-with-Filament#3]
![Screenshot (214)](https://github.com/YacoubAl-hardari/portfolio-with-Filament/assets/154662147/1d0b653a-8676-4e15-a9de-1b6b2e7a231e)
 

website link: https://faisalalhaj.com

**Comment by YacoubAl-hardari** [comment]
fixed an error show in Home page :: added the SoicalMedais
